eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.discovery.client.simple.local.uri}:${server.port}
  client:
    service-url:
        defaultZone : http://localhost:8671/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.0.193:3306/spring_cloud_sell?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name:  product
  cloud:
      discovery:
        client:
          simple:
            local:
              uri: 192.0.0.1
mybatis:
    #实体类所做包
    type-aliases-package: com.novli.product.entity
    #mapper.xml所在位置
    mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.novli.product.mapper : DEBUG
server:
  port: 8673
