eureka:
  client:
    service-url:
        defaultZone : http://localhost:8671/eureka/
  instance:
    hostname: product
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.0.193:3306/spring_cloud_sell?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name:  product
mybatis:
    #实体类所做包
    type-aliases-package: com.novli.product.entity
    #mapper.xml所在位置
    mapper-locations: classpath:mapper/*.xml
server:
  port: 8672
logging:
  level:
    com.novli.product.mapper : DEBUG
